baseURL = 'https://Ryuno-Shiki.github.io/'
languageCode = 'zh-cn'
title = '四季流乃的小破站'
theme = 'ryuno'

menu.main
name = '关于'
url = 'https://deft-blini-d16d4d.netlify.app/about'
weight = 2

menu.main
name = '友情链接'
url = 'https://deft-blini-d16d4d.netlify.app/friend'
weight = 3