baseURL = 'https://deft-blini-d16d4d.netlify.app/'
languageCode = 'zh-cn'
title = '四季流乃的小破站'
theme = 'ryuno'

[menu]
[[menu.main]]
identifier = 'about'
name = '关于'
url = '/about/'
weight = 10

[[menu.main]]
identifier = 'friend'
name = '友情链接'
url = '/friend/'
weight = 20